# Generated by Django 4.0.6 on 2022-08-01 16:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=2, help_text='М', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Длинна груза')),
                ('width', models.DecimalField(decimal_places=2, help_text='М', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ширина груза')),
                ('height', models.DecimalField(decimal_places=2, help_text='М', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Высота груза')),
                ('weight', models.DecimalField(decimal_places=2, help_text='КГ', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес')),
                ('volume', models.DecimalField(blank=True, decimal_places=3, help_text='Куб. м', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объем')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Имя')),
                ('surname', phonenumber_field.modelfields.PhoneNumberField(max_length=70, region=None, verbose_name='Фамилия')),
                ('telephone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('passport', models.CharField(max_length=25, unique=True, verbose_name='Номер пасспорта')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('surname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('telephone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('passport', models.CharField(max_length=25, unique=True, verbose_name='Номер пасспорта')),
                ('driver_license', models.CharField(max_length=25, unique=True, verbose_name='Номер прав')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('cargo_category', models.ManyToManyField(related_name='driver_categories', to='cargo_up.category', verbose_name='Категория груза')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('cargo', models.ManyToManyField(related_name='my_cargos', to='cargo_up.cargo', verbose_name='Мои грузы')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cargo_up.customer')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=25, verbose_name='Город')),
                ('country', models.CharField(max_length=25, verbose_name='Страна')),
                ('address', models.CharField(max_length=25, verbose_name='Адрес')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'ordering': ('-created_date',),
                'unique_together': {('country', 'city', 'address')},
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(max_length=25, verbose_name='Гос номер')),
                ('weight', models.DecimalField(decimal_places=3, help_text='В тоннах', max_digits=25, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Грузоподъемность')),
                ('volume', models.DecimalField(decimal_places=3, help_text='Куб. м', max_digits=25, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объем')),
                ('brend', models.CharField(max_length=25, verbose_name='Марка')),
                ('model', models.CharField(max_length=25, verbose_name='Модель')),
                ('vin_code', models.CharField(max_length=25, unique=True, verbose_name='VIN код')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('cargo_category', models.ManyToManyField(related_name='truck_categories', to='cargo_up.category', verbose_name='Категория груза')),
            ],
            options={
                'verbose_name': 'Грузовик',
                'verbose_name_plural': 'Грузовики',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='WayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('drivers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cargo_up.driver')),
                ('point_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waybill_loaction_a', to='cargo_up.location')),
                ('point_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waybill_loaction_b', to='cargo_up.location')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cargo_up.truck')),
            ],
            options={
                'verbose_name': 'Путевой лист',
                'verbose_name_plural': 'Путевые листы',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('invoice', models.ManyToManyField(related_name='orders', to='cargo_up.invoice', verbose_name='Заказ')),
                ('way_bill', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cargo_up.waybill')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created_date',),
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='point_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_loaction_a', to='cargo_up.location'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='point_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_loaction_b', to='cargo_up.location'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cargo_up.category', verbose_name='Категория'),
        ),
    ]
